services:
  # api:
  #   image: api-productos
  #   build: .
  #   ports:
  #     - ${PORT:-3000}:3000
  #   environment:
  #     MONGO_URL: ${MONGO_URL:-mongodb:27017}
  #     MONGO_DB: ${MONGO_DB}
  #     MONGO_USERNAME: ${MONGO_USERNAME}
  #     MONGO_PASSWORD: ${MONGO_PASSWORD}
  #   volumes:
  #     - ./src:/app/src
  #   command: npm run dev
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: web
      ME_CONFIG_MONGODB_ADMINPASSWORD: web1234
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/
      ME_CONFIG_BASICAUTH: "false"
